### PR TITLE
Update thevideo.py

### PR DESCRIPTION
**Pull request by MhhhxX**
if pairing dialog is cancelled raise ResolverError

### CODE REVIEW

**Comment by jsergio123** [comment]
Exceptions are raised in __check_auth()

https://github.com/jsergio123/script.module.urlresolver/commit/c002971059d633e5b292918c3c0cada577f665e3

**Comment by MhhhxX** [comment]
Yes you're right. My try except block was too much.
But if you manually cancel the dialog or if the countdown runs out, the `result` variable 
will be empty and Python will raise a TypeError in the following for loop because you 
can't iterate over a empty variable.
So before entering the loop I suggest:
`if not result`
`    raise ResolverError`
There is also another plugin file, where this is handled the same way. 
Look [openload.py](https://github.com/jsergio123/script.module.urlresolver/blob/master/lib/urlresolver/plugins/openload.py#L62) line 62-63

**Comment by jsergio123** [comment]
OK send the new pull requests

**Comment by jsergio123** [comment]
Or maybe I should handle it in the countdown dialog....

**Comment by MhhhxX** [comment]
Yes I think this is a good option, because it's very unlikely that plugin scripts have
to react, when the dialog is canceled. The dialog closes and that's it.

**Pull request closed without merging**
