### PR TITLE
Update indavideo.py

### PR DESCRIPTION
**Pull request by fractalsquirrel**
Tested and worked

### CODE REVIEW

**Comment by fractalsquirrel** [comment]
OK. I made a little change. This will do the job:
`            sources = []
            for value in video_files:
                match = re.search('\.(\d+)\.mp4', value)
                if match: sources.append((match.group(1), value))`

**Comment by jsergio123** [comment]
Can you post the link you are trying to resolve because the ones I try video_files return as a dict not a list. We might just need one more line to check for a dict. Thanks

**Comment by fractalsquirrel** [comment]
Can you reach the website (or videos)? I think the website (or videos) can't be reached outside of Hungary. Here is an example: [http://indavideo.hu/video/Big_Buck_Bunny](http://indavideo.hu/video/Big_Buck_Bunny)
I could play it in URLResolver Link Tester without VPN (in Hungary), but I couldn't play with VPN (I tried many locations - US, UK, Germany, France).

**Comment by fractalsquirrel** [comment]
OK, it works in every way. Thanks for your help.

**Pull request merged**
