### PR TITLE
Rapidgator plugin

### PR DESCRIPTION
**Pull request by kodistuff1**
Implemented as a universal resolver because some add-ons hard-code rapidgator (and other premium hosts) to only be accessible through a universal resolver.

### CODE REVIEW

**Comment by jsergio123** [comment]
you tested this?

**Comment by kodistuff1** [comment]
Yup! Only wrote this today, so might be a bit fresh, but it's working for me nicely.

**Comment by jsergio123** [comment]
hey rapidgator is a file host and not a universal resolver right?

**Comment by kodistuff1** [comment]
It is.

Unfortunately, some addons (Covenant, and I assume every other Genesis fork, possibly others) know that rapidgator is a premium host, and have been written to assume that it can only be accessed through debrid.

Without code changes, those add-ons will literally not show rapidgator sources, even though urlresolver tells them that they are supported.

Obviously, I have no way to make code changes to every project, so my solution was to rewrite it as a Universal Provider which only actually supports one host. If it helps, rapidgator's competition is the debrid services, so it almost makes sense to group them together as well.

My original thought was for a seperate 'Premium Hosts' category, but thought that was a bit too much for just one host!

If you don't like it, I can change it (should be as simple as removing the last three methods), but it will make it harder to actually use this resolver. No fault of yours, obviously!

**Comment by jsergio123** [comment]
The universal resolvers are for services like real debrid not premium file hosts. You can include rapidgator as a regular plugin and just specify the login settings. See here https://github.com/jsergio123/script.module.urlresolver/blob/master/lib/urlresolver/plugins/veeHD.py and here https://github.com/jsergio123/script.module.urlresolver/blob/master/lib/urlresolver/plugins/purevid.py

Make sure you set the default value for login to false.

**Comment by kodistuff1** [comment]
I guess I can fix Covenant.

> Make sure you set the default value for login to false.

Will do. Was having trouble working out what that setting was actually for, other than disabling stuff in settings.xml.

And on that subject...

```def _is_enabled(cls):
    # default behaviour is enabled is True if resolver is enabled, or has login set to "true", or doesn't have the setting
    return cls.get_setting('enabled') == 'true' and cls.get_setting('login') in ['', 'true']

I might be misreading this, but I think the code and comment disagrees. The code says 'and', but the comment says 'or'.

**Pull request merged**
